# Generated by Django 2.2.16 on 2020-12-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_overviews', '0022_courseoverviewtab_is_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='EolCourseProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(to='course_overviews.CourseOverview')),
            ],
        ),
    ]
