# Generated by Django 2.2.16 on 2020-12-03 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0022_courseoverviewtab_is_hidden'),
        ('eolcourseprogram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eolcourseprogram',
            name='final_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_course', to='course_overviews.CourseOverview'),
        ),
        migrations.AlterField(
            model_name='eolcourseprogram',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='course_overviews.CourseOverview'),
        ),
    ]
