# Generated by Django 2.2.16 on 2021-01-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eolcourseprogram', '0003_eolcourseprogram_final_course_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eolcourseprogram',
            name='final_course_mode',
            field=models.CharField(choices=[('no-id-professional', 'No-Id-Professional'), ('audit', 'Audit'), ('masters', "Master's"), ('professional', 'Professional'), ('honor', 'Honor'), ('credit', 'Credit'), ('verified', 'Verified')], default='honor', max_length=100),
        ),
    ]
