# Generated by Django 2.2.16 on 2021-01-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eolcourseprogram', '0005_auto_20210121_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eolcourseprogram',
            name='final_course_mode',
            field=models.CharField(blank=True, choices=[('professional', 'Professional'), ('masters', "Master's"), ('verified', 'Verified'), ('credit', 'Credit'), ('no-id-professional', 'No-Id-Professional'), ('audit', 'Audit'), ('honor', 'Honor')], help_text="Este valor se utiliza únicamente cuando el programa tiene definido un 'final course'. Si 'final course' está definido, y 'final course mode' está vacío, por defecto los estudiantes se inscribirán como 'honor'.", max_length=100, null=True),
        ),
    ]
