# Generated by Django 2.2.16 on 2021-01-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eolcourseprogram', '0006_auto_20210121_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eolcourseprogram',
            name='final_course_mode',
            field=models.CharField(blank=True, choices=[('credit', 'Credit'), ('professional', 'Professional'), ('audit', 'Audit'), ('verified', 'Verified'), ('honor', 'Honor'), ('no-id-professional', 'No-Id-Professional'), ('masters', "Master's")], help_text="Este valor se utiliza únicamente cuando el programa tiene definido un 'final course'. Si 'final course' está definido, y 'final course mode' está vacío, por defecto los estudiantes se inscribirán como 'honor'.", max_length=100, null=True),
        ),
    ]
